# Generated by Django 5.0.6 on 2024-06-22 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.person')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'accepted')])),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to='socialmedia.person')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='socialmedia.person')),
            ],
            options={
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
